### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by Killarnee** [Piwigo/Piwigo#1721] opened 2022-09-11 20:32 UTC
When I'm logged in and in any category page, eg. https://example.com/piwigo/index.php?/category/3, I get the following warning:

<b>Warning</b>:  Undefined array key "IS_IN_CADDIE" in <b>/srv/html/piwigo/_data/templates_c/1oivm68^b28a8459f5c203fb0f2c820e9728d5e1488fa528_0.file.public_controller.tpl.php</b> on line <b>174</b>

Server: Ubuntu 20.04, PHP 8.1 and Piwigo 13.0.0RC3

**Comment by MatthieuLP** [comment] 2022-09-14 08:46
I couldn't reproduce the issue, the caddie works fine for me.

**Comment by Killarnee** [comment] 2022-09-15 10:39
@MatthieuLP Then why is this with me?

![Screen Shot 2022-09-15 at 12 34 48 PM](https://user-images.githubusercontent.com/57904791/190383156-23de663c-7785-467e-8fec-7a96db0d64e4.png)

**Comment by MatthieuLP** [comment] 2022-09-19 09:04
I see that you use Admin tools, I installed it and now I reproduce the issue, working on it !

**Comment by MatthieuLP** [comment] 2022-09-19 10:40
Fixed the problem on the plugin repository and added a new release (AdminTools 12.3.1). Update your plugin and it should be fixed.

See commit here -> https://github.com/Piwigo/AdminTools/commit/14f9e68319b46b05e0de974fb77ec0e8651a2394

**Closed by MatthieuLP** 2022-09-19 10:40 UTC

**Comment by Killarnee** [comment] 2022-09-20 16:54
Thank you!
