### ISSUE TITLE
PHP incompatibility changes

### ISSUE THREAD

**Issue by syky01** [Piwigo/Piwigo#898] opened 2018-07-17 15:59 UTC
Hi,
I just check changes for PHP7.2 and some code still need be updated. (not only for PHP7.2)

Like using list() when function arguments are array members (check [https://3v4l.org/kCFQC](https://3v4l.org/kCFQC) )

e.g. used [here](https://github.com/Piwigo/Piwigo/blob/843ccb89c1997d551bc1fb5769c5fdaad9655082/include/picture_rate.inc.php#L40)

**Comment by plegall** [comment] 2018-07-17 20:48
Hi @syky01 

I don't understand what you mean. Does the code fails on PHP 7.2? Or is it just not written as it would be if we had started to code Piwigo with PHP 7.2 syntax available?

**Comment by plegall** [comment] 2018-07-23 13:21
I don't understand what the problem is exactly and I have no feedback from @syky01 . Let's close this issue :-/

**Closed by plegall** 2018-07-23 13:21 UTC
Labels: Status: Wont fix
