### ISSUE TITLE
Deleting a parent album leaves orphan photos and triggers errors when accessing the orphan and batch management sections

### ISSUE THREAD

**Issue by vitormarcal** [Piwigo/Piwigo#2253] opened 2024-10-25 12:20 UTC
After installing and setting up Piwigo, I created a hierarchical album structure as follows:

- Parent album: "Art"

    - Sub-albums: "Art1", "Art2", "Art3"

I uploaded several photos into these sub-albums. When I deleted the parent album "Art," I selected the option to keep the photos. Following this deletion, I encountered the following unexpected behavior:

1. Photos remained as orphans, and accessing the Orphan Photos, Batch Manager, or Recent Photos sections resulted in the following error:

```
Warning: Array to string conversion in /app/www/public/include/functions_category.inc.php on line 159

Fatal error: Uncaught mysqli_sql_exception: Unknown column 'Array' in 'where clause' in /app/www/public/include/dblayer/functions_mysqli.inc.php:132
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(132): mysqli->query()
#1 /app/www/public/include/functions_category.inc.php(161): pwg_query()
#2 /app/www/public/include/functions_html.inc.php(186): get_cat_info()
#3 /app/www/public/admin/include/batch_manager_filters.inc.php(119): get_cat_display_name_from_id()
#4 /app/www/public/admin/batch_manager_global.php(434): include('...')
#5 /app/www/public/admin/batch_manager.php(812): include('...')
#6 /app/www/public/admin.php(346): include('...')
#7 {main} thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 132
```

**Steps to Reproduce:**

    Create a parent album and add sub-albums.
    Upload photos to the sub-albums.
    Delete the parent album and select the option to retain photos.
    Access sections like Orphan Photos, Basket (I don't know if 'basket' is the correct word, my menu is in another language, sorry) , Batch Manager, or Recent Photos.

Edit: I dropped the database and started a new installation, and confirmed that this is indeed an error. I have inserted screenshots to better illustrate.

![Captura de tela de 2024-10-25 13-37-39](https://github.com/user-attachments/assets/d980543d-5918-4d80-918f-0a61533c3ae9)
![Captura de tela de 2024-10-25 13-39-50](https://github.com/user-attachments/assets/796c6a91-37d8-4d8e-bab8-41fde830ca62)

Expected Behavior: Parent and sub-albums should be deleted, the orphaned photos should not trigger an error in the Batch Manager or Orphan Photos sections.

**Comment by LintyDev** [comment] 2024-10-25 17:19
Hello, do you have the error without deleting orphan photos? 

As soon as you have the error, you can go to `Ferramentas > Manutenção` and perform the `Atualizar as informações das fotos`. This will perform an `invalidate_user_cache` which may solve your problem. We're still looking for a solution because in my case I can't reproduce your particular problem.

However, in Piwigo, when you delete a parent album that has sub-albums, all the albums are deleted and if you have photos they become orphaned.

**Comment by LintyDev** [comment] 2024-10-30 08:49
I was able to reproduce the problem, and we have a solution that will be in the next release (15.1.0)!

Thanks for your feedback! 😃

**Closed** 2024-10-31 11:14 UTC
