### ISSUE TITLE
How many category & photo can Piwigo hold in maximum?

### ISSUE THREAD

**Issue by nikolee** [Piwigo/Piwigo#906] opened 2018-07-31 06:58 UTC
Hi,

We're going to use Piwigo for building a big product image library, approx. 800,000 categories (incl. all sub-category), 5,000,000 photos at most.

I wonder if any issue on MySQL or Piwigo itself to limited hosting such in huge categories/photos on self-hosting server, any recommendations on the server hardware? Thanks!

Regards,
Niko Lee

**Comment by plegall** [comment] 2018-07-31 08:42
Hi @nikolee 

Huge numbers indeed!

I think 5M photos will be handled fine, if you have the appropriate power.

The 0.8M albums is much more complicated. In several places of Piwigo administration, we have some listbox with all albums. 800k albums will certainly break your page, whatever the power you have on server side. To handle such an amount of albums, we would need to completely change the way albums are listed, for example on the edition page of a photo.

**Comment by plegall** [comment] 2018-07-31 09:01
I have here an example of Piwigo with 12k albums. The edition page of a photo takes several seconds to load (but ends up working) just to display the related albums. With 800k albums (66 times more) I think your web browser will have critical difficulties :-/

**Comment by nikolee** [comment] 2018-07-31 16:29
Hi @plegall, thanks reply!!!

If I deploy Piwigo on my corporate office, and all users are internal users access via LAN, will the performance significantly improve?

I think we should make some customization on listing 800K albums. 1) display top 15 most recent update albums; 2) Use tags instead for the pictures category, not using albums; Limited the number of albums keeps unchanged frequently. How do you think?

**Comment by plegall** [comment] 2018-08-01 10:36
The LAN (Local Area Network, meaning not using the internet) won't change the problem. The problem is loading a list of 800k albums in your web browser.

To solve this problem there is not many solutions, we need a completely "remote loading with filter and loading only the X first albums". We can also have some smart things like "display 10 most recently updated/created albums" too, yes :-)

This is an important change, with quite a big impact. I hope I can work on it for Piwigo 3.0.

Using tags won't really solve the problem. Use tags if it's relevant to your usage :-) Tags are loaded in pages exactly the same way as albums. You're going to get uncomfortable with 10k tags, for sure.

**Comment by nikolee** [comment] 2018-08-01 13:53
Good to know there is a solution to the big problem!!! Really appreciated you put this into your development roadmap. Do you have a general idea on the release of Piwigo 3.0? So I could discuss with the team to understand the progress the image library setup.

**Comment by plegall** [comment] 2021-11-25 08:42
I'm reading this issue 3 years after and the "problem" is still a problem. I've worked with a 15k albums gallery and some administration pages are slow to load. For example the "album mover"...

**Comment by plegall** [comment] 2022-08-19 08:03
The upcoming version 13 of Piwigo brings a first solution to the "many albums issue" (many = more than 10k). When editing a photo, you can link the photo to albums. Until Piwigo 12, it was a full list of albums. We have replaced this list by a "popin with a search field".

![piwigo-13-linked-albums](https://user-images.githubusercontent.com/9326959/185572817-9bea7818-8309-42d3-95bc-c713a826ff07.gif)

I'm going to close this issue, even if I know there is still work to do be able to handle 800k albums everywhere. We need to deploy this kind of widget everywhere.

**Closed by plegall** 2022-08-19 08:03 UTC
Labels: Type: Question
