### ISSUE TITLE
zombie album (category with NULL uppercats)

### ISSUE THREAD

**Issue by D33M0N** [Piwigo/Piwigo#1389] opened 2021-04-30 17:40 UTC
Somehow we got an undeletable (because can't open "edit page" where the delete button is) zombie album.
Any help how to get rid of it?
Piwigo 11.4.0

When I try to "Visit the gallery" from admin, I get:
URL: /index.php?/category/60460
```
<pre><br />
<b>Warning</b>:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 7

SELECT 
  id, name, permalink, nb_images, global_rank,
  date_last, max_date_last, count_images, count_categories
FROM categories INNER JOIN user_cache_categories
  ON id = cat_id and user_id = 51
WHERE 
(id_uppercat is NULL OR id_uppercat IN ())
; in <b>/var/www/html/galerii/include/dblayer/functions_mysqli.inc.php</b> on line <b>864</b><br />
</pre><br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/galerii/include/dblayer/functions_mysqli.inc.php:228
Stack trace:
#0 /var/www/html/galerii/include/functions_category.inc.php(106): pwg_db_fetch_assoc(false)
#1 /var/www/html/galerii/include/menubar.inc.php(98): get_categories_menu()
#2 /var/www/html/galerii/include/menubar.inc.php(15): initialize_menu()
#3 /var/www/html/galerii/index.php(103): include('/var/www/html/g...')
#4 {main}
  thrown in <b>/var/www/html/galerii/include/dblayer/functions_mysqli.inc.php</b> on line <b>228</b><br />
```

When I click edit on it in admin.php I get:
URL: /admin.php?page=album-60460
```
<pre><br />
<b>Warning</b>:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4

SELECT
    DISTINCT(image_id)
  FROM image_category
  WHERE category_id IN ()
 ; in <b>/var/www/html/galerii/include/dblayer/functions_mysqli.inc.php</b> on line <b>864</b><br />
</pre><br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/galerii/include/dblayer/functions_mysqli.inc.php:925
Stack trace:
#0 /var/www/html/galerii/admin/cat_modify.php(199): query2array('\nSELECT\n    DIS...', NULL, 'image_id')
#1 /var/www/html/galerii/admin/album.php(60): include('/var/www/html/g...')
#2 /var/www/html/galerii/admin.php(298): include('/var/www/html/g...')
#3 {main}
  thrown in <b>/var/www/html/galerii/include/dblayer/functions_mysqli.inc.php</b> on line <b>925</b><br />
```

**Comment by D33M0N** [comment] 2021-04-30 20:03
nvm. for some reason in the SQL this category lacked value for "uppercats" (was NULL). added its own number and was able to edit and delete it. Dunno really how this could have happened. Any clues?

**Comment by plegall** [comment] 2021-05-03 10:21
No clue how it happened, but there is a specific maintenance task for this on [Admin > Tools > Maintenance].

**Comment by D33M0N** [comment] 2021-05-03 19:02
> No clue how it happened, but there is a specific maintenance task for this on [Admin > Tools > Maintenance].

which one of them?

**Comment by plegall** [comment] 2021-05-04 08:29
> Update albums' information

**Comment by plegall** [comment] 2021-05-07 12:44
Since we don't know how the album became zombie (thus impossible to reproduce), I close this issue.

**Closed by plegall** 2021-05-07 12:44 UTC
